version: "3.8"

services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_container
    ports:
      - "9000:9000"  # Mapear el puerto 9000 del contenedor al puerto 9000 del host
    volumes:
      - .:/app  # Montar el directorio actual para desarrollo
    command: python app.py